name: carriertrack_flutter
description: A cross-platform CarrierTrack app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  provider: ^6.0.5
  camera: ^0.11.1
  mobile_scanner: ^6.0.7
  path_provider: ^2.0.12
  geolocator: ^13.0.3
  permission_handler: ^11.4.0
  sqflite: ^2.2.5
  path: ^1.8.3
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demoRoutes/demo_data.txt
